// Catálogo Elegance - solo perfumes
// price = costo de reposición de referencia (US$, catálogo del proveedor)
// final = precio de venta RETAIL USD = price * (1 + margen retail del segmento)
// notes = pirámide olfativa (salida / corazón / fondo)
// Segmentos con margen diferenciado: arabe (agresivo) / mid / nicho / lujo

const SEGMENT_FALLBACK = "mid";
const SEGMENT_BY_BRAND = {
  LATTAFA: "arabe",
  ARMAF: "arabe",
  "AL WATANIAH": "arabe",
  AFNAN: "arabe",
  RASASI: "arabe",
  "DAR EL WARD": "arabe",
  "FRENCH AVENUE": "nicho",
  XERJOFF: "nicho",
  DIOR: "lujo",
  LANCOME: "lujo",
  "CAROLINA HERRERA": "lujo"
};
// Margen retail (web) por segmento, en USD sobre el costo de reposición
const RETAIL_MARGIN = { arabe: 0.5, mid: 0.65, nicho: 0.8, lujo: 0.9 };

const PRODUCTS = [
  { id: 198376, brand: "ARMAF", name: "Odyssey Dubai Chocolat EDP 100ml", gender: "U", price: 16.99, img: "img/products/198376.png", notes: { top: "café, pistacho, avellana, praliné, knafé", heart: "chocolate, vainilla, cardamomo", base: "caramelo, haba tonka, maderas ámbar" } },
  { id: 204757, brand: "LATTAFA", name: "Fakhar Platin EDP 100ml", gender: "U", price: 22.00, img: "img/products/204757.png", notes: { top: "bergamota, pimienta rosa, cardamomo", heart: "guayaba, lavanda, jengibre", base: "incienso, palo santo, sándalo" } },
  { id: 12091, brand: "JACQUES BOGART", name: "Silver Scent EDT 100ml", gender: "M", price: 20.00, img: "img/products/12091.png", notes: { top: "azahar, limón", heart: "lavanda, cardamomo, nuez moscada, romero, cilantro, geranio", base: "litchi, haba tonka, madera de teca, vetiver" } },
  { id: 198826, brand: "CAROLINA HERRERA", name: "212 Vip Rosé EDP 80ml", gender: "F", price: 75.00, img: "img/products/198826.png", notes: { top: "champán rosado, pimienta rosa", heart: "flor de melocotón, rosa", base: "almizcle blanco, notas amaderadas" } },
  { id: 906799, brand: "MONT BLANC", name: "Legend EDT 100ml", gender: "M", price: 37.99, img: "img/products/906799.png", notes: { top: "lavanda, piña, bergamota, verbena de limón", heart: "manzana roja, frutas secas, musgo de roble, geranio, cumarina, rosa", base: "haba tonka, sándalo" } },
  { id: 200710, brand: "ARMAF", name: "Odyssey Mega EDP 100ml", gender: "M", price: 22.00, img: "img/products/200710.png", notes: { top: "naranja, bergamota, limón, jengibre, menta", heart: "piña, salvia, enebro, geranio", base: "almizcle, cedro, haba tonka, vetiver" } },
  { id: 13329, brand: "AL WATANIAH", name: "Ameerati EDP 100ml", gender: "F", price: 12.50, img: "img/products/13329.png", notes: { top: "almizcle, cítricos, notas verdes", heart: "notas herbales, notas amaderadas", base: "notas empolvadas, notas especiadas" } },
  { id: 200720, brand: "ARMAF", name: "Odyssey Aqua EDP 100ml", gender: "M", price: 26.00, img: "img/products/200720.png", notes: { top: "pomelo, naranja, artemisa", heart: "lavanda, menta", base: "ciprés, pachulí, ambroxán" } },
  { id: 95418, brand: "ARMAF", name: "Odyssey Candee EDP 100ml", gender: "F", price: 16.99, img: "img/products/95418.png", notes: { top: "fresa, frambuesa, bergamota, geranio, melocotón", heart: "caramelo, jazmín, maracuyá", base: "pachulí, almizcle, ámbar" } },
  { id: 117299, brand: "ARMAF", name: "Odyssey Tyrant EDP 100ml", gender: "M", price: 22.00, img: "img/products/117299.png", notes: { top: "pomelo, notas cítricas", heart: "pimienta, lavanda, geranio, elemi", base: "vetiver, cedro, notas amaderadas, ambroxán" } },
  { id: 117323, brand: "ARMAF", name: "Odyssey Aoud EDP 100ml", gender: "M", price: 22.00, img: "img/products/117323.png", notes: { top: "azafrán, nuez moscada, lavanda", heart: "oud, notas amaderadas", base: "ambroxán, almizcle, pachulí" } },
  { id: 103193, brand: "ARMAF", name: "Odyssey Limoni EDP 100ml", gender: "U", price: 22.00, img: "img/products/103193.png", notes: { top: "limón, naranja dulce, mandarina, bergamota", heart: "jengibre, azahar, notas marinas", base: "té, almizcle, ámbar" } },
  { id: 206109, brand: "ARMAF", name: "Island Bliss EDP 100ml", gender: "F", price: 36.00, img: "img/products/206109.png", notes: { top: "bayas, notas verdes", heart: "coco, lactonas, azahar, nenúfar", base: "vainilla, haba tonka, almizcle" } },
  { id: 673880, brand: "FERRARI", name: "Scuderia Black EDT 125ml", gender: "M", price: 19.00, img: "img/products/673880.png", notes: { top: "manzana, ciruela, cítricos, lima, bergamota", heart: "canela, jazmín, cardamomo, rosa", base: "vainilla, ámbar, cedro, almizcle" } },
  { id: 238887, brand: "LATTAFA", name: "Asad Elixir EDP 100ml", gender: "M", price: 28.00, img: "img/products/238887.png", notes: { top: "pimienta negra, tabaco, piña", heart: "pachulí, café, iris", base: "vainilla, ámbar, madera seca, benzoína, labdano" } },
  { id: 43387, brand: "LATTAFA", name: "Mayar EDP 100ml", gender: "F", price: 20.00, img: "img/products/43387.png", notes: { top: "lichi, frambuesa, hoja de violeta", heart: "rosa blanca, peonía, jazmín", base: "almizcle, vainilla" } },
  { id: 62120, brand: "LATTAFA", name: "Niche Emarati Khanjar EDP 85ml", gender: "U", price: 38.00, img: "img/products/62120.png", notes: { top: "nuez moscada, jengibre, pimiento", heart: "cashmerán, violeta, pachulí", base: "vetiver, incienso, almizcle, cuero" } },
  { id: 211935, brand: "AL WATANIAH", name: "Sabah Al Ward Sugar EDP 100ml", gender: "F", price: 20.00, img: "img/products/211935.png", notes: { top: "fresa, frambuesa, arándano, grosella negra, cereza", heart: "jazmín, violeta", base: "ámbar, almizcle, pétalos de rosa, vainilla, musgo de roble, cashmerán" } },
  { id: 21394, brand: "LATTAFA", name: "Pride Ansaam Gold EDP 100ml", gender: "U", price: 21.00, img: "img/products/21394.png", notes: { top: "mandarina, pera", heart: "notas dulces, jazmín, rosa", base: "almizcle, vainilla, frambuesa" } },
  { id: 66594, brand: "LATTAFA", name: "Yara Tous EDP 100ml", gender: "F", price: 20.00, img: "img/products/66594.png", notes: { top: "mango, coco, maracuyá", heart: "jazmín, azahar, heliotropo", base: "vainilla, almizcle, cashmerán" } },
  { id: 735307, brand: "LANCOME", name: "La Vie Est Belle EDP 100ml", gender: "F", price: 80.00, img: "img/products/735307.png", notes: { top: "grosella negra, pera", heart: "iris, jazmín, azahar", base: "praliné, vainilla, pachulí, haba tonka" } },
  { id: 43253, brand: "LATTAFA", name: "Yara Moi EDP 100ml", gender: "F", price: 20.00, img: "img/products/43253.png", notes: { top: "jazmín, melocotón", heart: "caramelo, ámbar", base: "pachulí, sándalo" } },
  { id: 42533, brand: "CALVIN KLEIN", name: "CK Be EDT 100ml", gender: "U", price: 22.00, img: "img/products/42533.png", notes: { top: "lavanda, notas verdes, bergamota, menta, enebro, mandarina", heart: "hierba verde, jazmín, melocotón, fresia, magnolia, orquídea", base: "ámbar, cedro, opopónax, sándalo, vainilla, almizcle" } },
  { id: 5767, brand: "LATTAFA", name: "Hayaati Gold Elixir EDP 100ml", gender: "U", price: 11.00, img: "img/products/5767.png", notes: { top: "pomelo, bergamota, casis", heart: "melocotón, azafrán, cuero", base: "vetiver, vainilla, acorde almizcle-ámbar" } },
  { id: 2057, brand: "AL WATANIAH", name: "Sabah Al Ward EDP 100ml", gender: "F", price: 18.00, img: "img/products/2057.png", notes: { top: "mandarina, pimienta rosa", heart: "cacao, azahar, jazmín sambac", base: "vainilla, haba tonka, pachulí" } },
  { id: 2046, brand: "AL WATANIAH", name: "Durrat Al Aroos EDP 85ml", gender: "F", price: 14.00, img: "img/products/2046.png", notes: { top: "almizcle blanco, cipriol", heart: "vainilla, cardamomo, azafrán", base: "madera de guayaco, cumarina" } },
  { id: 2002, brand: "AL WATANIAH", name: "Attar Al Wesal EDP 100ml", gender: "M", price: 13.50, img: "img/products/2002.png", notes: { top: "pera, lavanda, menta, bergamota, limón", heart: "canela, salvia esclarea, comino", base: "vainilla negra, ámbar, cedro, pachulí" } },
  { id: 120901, brand: "LATTAFA", name: "Victoria EDP 100ml", gender: "F", price: 25.00, img: "img/products/120901.png", notes: { top: "pastel de limón, merengue", heart: "neroli", base: "vainilla" } },
  { id: 15713, brand: "LATTAFA", name: "Ana Abiyedh Rouge EDP 60ml", gender: "U", price: 11.50, img: "img/products/15713.png", notes: { top: "geranio, vainilla, almizcle blanco, azafrán", heart: "cardamomo, azafrán, vainilla", base: "madera de guayaco, almizcle blanco, jazmín, nagarmotha" } },
  { id: 51184, brand: "LATTAFA", name: "Pride Ishq Al Shuyukh Gold EDP 100ml", gender: "F", price: 22.00, img: "img/products/51184.png", notes: { top: "caramelo, azafrán", heart: "haba tonka, ante, cuero", base: "ámbar, vainilla, almizcle" } },
  { id: 68339, brand: "LATTAFA", name: "Khamrah Qahwa EDP 100ml", gender: "U", price: 24.00, img: "img/products/68339.png", notes: { top: "canela, cardamomo, jengibre", heart: "praliné, frutas confitadas, flores blancas", base: "café, vainilla, haba tonka, benzoína, almizcle" } },
  { id: 923170, brand: "CALVIN KLEIN", name: "CK One EDT 100ml", gender: "U", price: 21.99, img: "img/products/923170.png", notes: { top: "limón, notas verdes, bergamota, mandarina, piña, cardamomo", heart: "lirio de los valles, jazmín, violeta, rosa, nuez moscada, fresia", base: "almizcle, cedro, té verde, sándalo, musgo de roble, ámbar" } },
  { id: 215737, brand: "ARMAF", name: "Odyssey Go Mango EDP 100ml", gender: "U", price: 26.00, img: "img/products/215737.png", notes: { top: "limón, pimienta rosa, jengibre, flores blancas", heart: "mango, haba tonka, maderas secas", base: "vainilla, ámbar, madera de guayaco, almizcle" } },
  { id: 887471, brand: "ANIMALE", name: "Animale For Men EDT 100ml", gender: "M", price: 16.00, img: "img/products/887471.png", notes: { top: "piña, lavanda, lima, gálbano, limón", heart: "miel, nuez moscada, ylang-ylang, rosa, jazmín", base: "vainilla, tabaco, pachulí, ámbar, sándalo, almizcle" } },
  { id: 13318, brand: "AL WATANIAH", name: "Ghala EDP 100ml", gender: "F", price: 11.00, img: "img/products/13318.png", notes: { top: "azafrán, jazmín", heart: "madera ámbar, ámbar gris", base: "resina de abeto, cedro" } },
  { id: 62175, brand: "LATTAFA", name: "Bade'e Al Oud Sublime EDP 100ml", gender: "U", price: 20.00, img: "img/products/62175.png", notes: { top: "manzana, lichi, rosa", heart: "jazmín, ciruela", base: "musgo, pachulí, vainilla" } },
  { id: 38975, brand: "LATTAFA", name: "Al Noble Safeer EDP 100ml", gender: "U", price: 22.00, img: "img/products/38975.png", notes: { top: "jengibre, pimienta negra, bergamota, pomelo", heart: "heliotropo, jazmín, caramelo", base: "almizcle, cipriol, cachemira, ámbar gris, vainilla, guayaco" } },
  { id: 905844, brand: "ARMAF", name: "Club de Nuit Women EDP 105ml", gender: "F", price: 28.00, img: "img/products/905844.png", notes: { top: "bergamota, pomelo, melocotón, naranja", heart: "geranio, jazmín, lichi, rosa", base: "almizcle, pachulí, vainilla, vetiver" } },
  { id: 943284, brand: "ARMAF", name: "Club de Nuit Milestone EDP 105ml", gender: "U", price: 29.00, img: "img/products/943284.png", notes: { top: "bergamota, frutos rojos, acorde marino", heart: "violeta, sándalo, maderas blancas", base: "vetiver, almizcle, ambroxan" } },
  { id: 943295, brand: "ARMAF", name: "Club de Nuit Sillage EDP 100ml", gender: "U", price: 30.00, img: "img/products/943295.png", notes: { top: "bergamota, limón, lima, jengibre, hoja de violeta, grosella negra", heart: "jazmín, iris, rosa", base: "sándalo, almizcle, ambroxan, cedro" } },
  { id: 23464, brand: "ARMAF", name: "Club de Nuit Untold EDP 105ml", gender: "U", price: 33.00, img: "img/products/23464.png", notes: { top: "jazmín, azafrán", heart: "ámbar gris, madera ámbar", base: "cedro, resina de abeto" } },
  { id: 94620, brand: "LATTAFA", name: "Angham EDP 100ml", gender: "U", price: 22.00, img: "img/products/94620.png", notes: { top: "jengibre, mandarina, pimienta rosa", heart: "lavanda, praliné, cacao, jazmín", base: "vainilla, ámbar, almizcle" } },
  { id: 2024, brand: "AL WATANIAH", name: "Sultan Al Lail EDP 100ml", gender: "M", price: 10.50, img: "img/products/2024.png", notes: { top: "naranja sanguina, bayas de enebro, cítricos, limón siciliano", heart: "lavanda, pimento, salvia esclarea, geranio", base: "vetiver, cedro, pachulí" } },
  { id: 200753, brand: "ARMAF", name: "Club de Nuit Maleka EDP 105ml", gender: "F", price: 36.00, img: "img/products/200753.png", notes: { top: "lichi, bergamota, pimienta rosa", heart: "iris (orris)", base: "praliné, sándalo, ambroxan" } },
  { id: 886986, brand: "DIOR", name: "Sauvage EDP 100ml", gender: "M", price: 108.00, img: "img/products/886986.png", notes: { top: "bergamota", heart: "pimienta de sichuan, lavanda, anís estrellado, nuez moscada", base: "ambroxan, vainilla" } },
  { id: 201700, brand: "DAR EL WARD", name: "Dalal EDP 100ml", gender: "F", price: 32.00, img: "img/products/201700.png", notes: { top: "frutal, cítrico, ácido", heart: "floral, fresco, terroso", base: "almizclado, ahumado" } },
  { id: 103733, brand: "LATTAFA", name: "Mayar Cherry Intense EDP 100ml", gender: "F", price: 20.00, img: "img/products/103733.png", notes: { top: "fresa, bergamota", heart: "mermelada de cereza, cacao", base: "vainilla, pachulí, ámbar" } },
  { id: 200786, brand: "ARMAF", name: "Club de Nuit Lionheart Woman EDP 100ml", gender: "F", price: 30.00, img: "img/products/200786.png", notes: { top: "lavanda, menta", heart: "benzoína, vainilla", base: "miel, haba tonka, tabaco" } },
  { id: 205938, brand: "AFNAN", name: "Turathi Electric EDP 90ml", gender: "U", price: 30.00, img: "img/products/205938.png", notes: { top: "bergamota, pomelo rosa, pera, mandarina", heart: "manzana, cedro, azahar", base: "vainilla, ámbar seco, almizcle, ambroxan" } },
  { id: 23453, brand: "ARMAF", name: "Club de Nuit Iconic EDP 105ml", gender: "M", price: 30.00, img: "img/products/23453.png", notes: { top: "pomelo, limón, menta, pimienta rosa, cilantro", heart: "jengibre, nuez moscada, melón, jazmín", base: "incienso, ámbar, cedro, sándalo, pachulí, ládano" } },
  { id: 26243, brand: "LATTAFA", name: "Yara EDP 100ml", gender: "F", price: 25.00, img: "img/products/26243.png", notes: { top: "orquídea, heliotropo, mandarina", heart: "acorde goloso, frutas tropicales", base: "vainilla, almizcle, sándalo" } },
  { id: 39673, brand: "AL WATANIAH", name: "Oud Mystery Intense EDP 100ml", gender: "U", price: 16.50, img: "img/products/39673.png", notes: { top: "nuez moscada, azafrán, lavanda", heart: "oud (madera de agar)", base: "almizcle, pachulí" } },
  { id: 38964, brand: "LATTAFA", name: "Al Noble Wazeer EDP 100ml", gender: "U", price: 22.00, img: "img/products/38964.png", notes: { top: "manzana, coñac, nuez moscada, azafrán", heart: "whisky, roble, cedro, sándalo", base: "almizcle, mirra, ambroxan, vainilla" } },
  { id: 39190, brand: "LATTAFA", name: "Al Noble Ameer EDP 100ml", gender: "U", price: 22.00, img: "img/products/39190.png", notes: { top: "pimienta rosa, manzana, romero", heart: "clavo de olor, notas florales", base: "oud, pachulí, ládano, ciprés, vetiver" } },
  { id: 241870, brand: "RASASI", name: "Hawas Kobra EDP 100ml", gender: "M", price: 34.00, img: "img/products/241870.png", notes: { top: "jengibre, bergamota, mandarina", heart: "té verde, neroli, canela", base: "almizcle, maderas, ámbar" } },
  { id: 38997, brand: "LATTAFA", name: "Emaan EDP 100ml", gender: "F", price: 20.00, img: "img/products/38997.png", notes: { top: "bergamota, grosella negra, azahar", heart: "nardo, jazmín, caléndula", base: "almizcle blanco, cedro, vainilla, pachulí" } },
  { id: 103239, brand: "ARMAF", name: "Odyssey Mandarin Sky EDP 100ml", gender: "M", price: 24.00, img: "img/products/103239.png", notes: { top: "mandarina, naranja, azafrán, salvia", heart: "caramelo, haba tonka, caléndula", base: "ambroxan, cedro, vetiver" } },
  { id: 225200, brand: "ARMAF", name: "Club de Nuit Bling EDP 75ml", gender: "U", price: 36.00, img: "img/products/225200.png", notes: { top: "cítricos", heart: "prisma floral, polvo de estrellas", base: "vainilla, madera terciopelo" } },
  { id: 97958, brand: "FRENCH AVENUE", name: "Liquid Brun EDP 100ml", gender: "M", price: 35.00, img: "img/products/97958.png", notes: { top: "canela, bergamota, cardamomo, azahar", heart: "vainilla bourbon, elemi", base: "almizcle, praliné, ambroxan, guayaco" } },
  { id: 200237, brand: "RASASI", name: "Hawas Black EDP 100ml", gender: "M", price: 32.00, img: "img/products/200237.png", notes: { top: "bergamota, piña, pomelo", heart: "pachulí, cedro, jazmín", base: "musgo de roble, maderas, ámbar" } },
  { id: 887875, brand: "ARMAF", name: "Club de Nuit Intense EDT 105ml", gender: "M", price: 30.00, img: "img/products/887875.png", notes: { top: "limón, piña, bergamota, grosella negra, manzana", heart: "abedul, jazmín, rosa", base: "almizcle, ámbar gris, pachulí, vainilla" } },
  { id: 26300, brand: "LATTAFA", name: "Asad EDP 100ml", gender: "M", price: 24.00, img: "img/products/26300.png", notes: { top: "pimienta negra, piña, tabaco", heart: "café, pachulí, iris", base: "ámbar, vainilla, maderas secas, benzoína, ládano" } },
  { id: 971981, brand: "AFNAN", name: "9PM EDP 100ml", gender: "M", price: 26.00, img: "img/products/971981.png", notes: { top: "bergamota, lavandina, canela, manzana", heart: "muguet, azahar", base: "pachulí, ámbar, vainilla, haba tonka" } },
  { id: 592005, brand: "CAROLINA HERRERA", name: "212 EDT 100ml", gender: "M", price: 61.99, img: "img/products/592005.png", notes: { top: "notas verdes, pomelo, especias, bergamota, lavanda, petitgrain", heart: "jengibre, violeta, gardenia, salvia", base: "almizcle, sándalo, vetiver, incienso, guayaco, ládano" } },
  { id: 999622, brand: "XERJOFF", name: "Erba Pura EDP 100ml", gender: "U", price: 139.99, img: "img/products/999622.png", notes: { top: "naranja siciliana, bergamota de calabria, limón siciliano", heart: "notas frutales", base: "almizcle blanco, vainilla de madagascar, ámbar" } },
  { id: 92672, brand: "LATTAFA", name: "The Kingdom EDP F 100ml", gender: "F", price: 20.00, img: "img/products/92672.png", notes: { top: "pera, peonía, grosella negra", heart: "jazmín, praliné, haba tonka", base: "vainilla, sándalo, ámbar, almizcle" } },
  { id: 9591, brand: "ARMAF", name: "Club de Nuit Urban Man Elixir EDP 105ml", gender: "M", price: 30.00, img: "img/products/9591.png", notes: { top: "bergamota, pimienta rosa, jazmín, azahar", heart: "lavanda, tagetes, geranio, vetiver, elemi, azafrán", base: "ámbar, ambroxan, pachulí, cedro, ládano" } },
  { id: 200551, brand: "FRENCH AVENUE", name: "Vulcan Feu EDP 100ml", gender: "U", price: 36.00, img: "img/products/200551.png", notes: { top: "mango, jengibre, limón, ruibarbo", heart: "jazmín, violeta, praliné, pimienta rosa", base: "haba tonka, cedro, ámbar gris, musgo" } },
  { id: 41699, brand: "AFNAN", name: "9AM Dive EDP 100ml", gender: "U", price: 24.50, img: "img/products/41699.png", notes: { top: "limón, pimienta rosa, menta, grosella negra", heart: "manzana, incienso, cedro", base: "pachulí, jazmín, jengibre, sándalo" } },
  { id: 202700, brand: "CAROLINA HERRERA", name: "212 Vip EDT 100ml", gender: "M", price: 64.00, img: "img/products/202700.png", notes: { top: "maracuyá, lima, pimienta, jengibre", heart: "vodka, ginebra, menta, especias", base: "ámbar, cuero, maderas" } },
  { id: 102473, brand: "LATTAFA", name: "Afeef EDP 100ml", gender: "F", price: 58.00, img: "img/products/102473.png", notes: { top: "melocotón, pimienta rosa, bergamota", heart: "nardo, azahar, jazmín", base: "praliné, ámbar, sándalo, pachulí" } },
  { id: 92661, brand: "LATTAFA", name: "The Kingdom EDP M 100ml", gender: "M", price: 28.00, img: "img/products/92661.png", notes: { top: "salvia, lavanda, menta", heart: "tabaco, vainilla, azahar", base: "benzoína, haba tonka, ládano" } },
  { id: 74448, brand: "XERJOFF", name: "Erba Gold EDP 100ml", gender: "U", price: 159.99, img: "img/products/74448.png", notes: { top: "limón de amalfi, naranja brasileña, bergamota de calabria, jengibre", heart: "clavo de olor, manzana verde, cardamomo, melón, pera", base: "ámbar, vainilla de madagascar, almizcle, maderas" } },
  { id: 253693, brand: "LATTAFA", name: "Khamrah Waha EDP 100ml", gender: "U", price: 45.00, img: "img/products/253693.png", notes: { top: "bergamota, yuzu, enebro, jengibre", heart: "iris, pepino, sal marina, salvia", base: "vainilla, haba tonka, almizcle, ambrofix, akigalawood" } },
  { id: 235862, brand: "AFNAN", name: "9PM Night Out Extrait 100ml", gender: "U", price: 45.00, img: "img/products/235862.png", notes: { top: "fruta del dragón, bergamota, coñac, lavanda, manzana", heart: "cardamomo, mahonial, ante, toffee, cedro", base: "haba tonka, akigalawood, ambrofix, pachulí" } },
  { id: 82570, brand: "LATTAFA", name: "Teriaq EDP 100ml", gender: "U", price: 24.00, img: "img/products/82570.png", notes: { top: "pimienta rosa, caramelo, almendra amarga, albaricoque", heart: "miel, flores blancas, ruibarbo, rosa", base: "vainilla, cuero, ládano, almizcle, vetiver" } },
  { id: 203229, brand: "LATTAFA", name: "Atheeri EDP 100ml", gender: "F", price: 55.00, img: "img/products/203229.png", notes: { top: "flor de la pasión, gotas de rocío", heart: "orquídea, jazmín", base: "vainilla, madera ámbar" } },
];

// Precio retail (USD) con margen diferenciado por segmento
PRODUCTS.forEach((p) => {
  p.seg = SEGMENT_BY_BRAND[p.brand] || SEGMENT_FALLBACK;
  p.final = Math.round(p.price * (1 + (RETAIL_MARGIN[p.seg] || RETAIL_MARGIN.mid)) * 100) / 100;
});